######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 7 15:04:45 2012
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += ..

QT += core \
    gui \
    opengl

# Input
HEADERS += ../impact.h ../vect.h draw.h
SOURCES += ../impact.cpp main.cpp ../vect.cpp \
    ../impact_physics.cpp \
    ../impact_settings.cpp \
    draw.cpp
